services:
  service:
    image: demo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/assignment
    build:
      dockerfile: ./Dockerfile
    ports:
      - 3000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: assignment

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
